### ISSUE TITLE
First message for Olga 

### ISSUE THREAD

**Issue by KosNet75** [BaMnu/chat-bot-telegram#1]
Dear TeamLead Olka, I hasten to inform you, I am already here. You should know that I am against slave labor, and I also think that difficult teenagers should not be forced to work hard a lot.)) Google translator is bull shit! We don't understand each other)))

**Comment by BaMnu** [comment]
Shut up and WORK!

**Comment by KosNet75** [comment]
Нихт партизанен! Ферштейн? Зер гут! )

**Comment by BaMnu** [comment]
Костян, надо в Storage сделать выбор String с цитатой с классом Random random (ну или как-нить еще), чтобы на печать выходила одна рандомная цитата, а не весь список. Работаем пока в ветке **text** и заливаем все туда, как бот будет готов зальем в master

**Comment by KosNet75** [comment]
Уважаемая monamour Ольга.. Ты решила меня с разбегу в дедлайн рожей макнуть?)))) Не можу я сегожня). Сделаю не вопрос. Рандом легко(у меня есть, использовал), а вывод строк я думаю нужно делать через буфер и цикл по количеству знаков(допустим что бы в каждой строке было по 200(примерно) символов, тобишь можно посчитать количество не выводимых строк до нужной и вывести только ее. Ну это первое что в голову пришло, а так то подумать надо(даже мне))))))).

**Comment by KosNet75** [comment]
Тобишь каждой цитате присвоить номер, коий будет соответствовать номеру строки, в цикле считать до него и выводить только его.. ну говорю, это только первая мысль. Ольча, вечером посмотрю или завтра если сегодня все совсем затянется.

**Comment by BaMnu** [comment]
https://github.com/BaMnu/chat-bot-telegram/blob/5bbd7c41d248eee37770c3e2a176e69945bc72ef/src/main/java/bot/Storage.java#L22-L26

Вместо вывода нужен метод, который возвращает случайную строку из списка 
Не забывай пока заливать в ветку text только

Вывод делала просто, чтоб проверить работает ли чтение текстового документа

Попробуй разные способы, ты также можешь править мой код, если тебе не нравится что-то
